$(document).ready(function(){$("#session_info_d").dialog({autoOpen:!1,resizable:!1,width:300,height:"auto",minHeight:0,modal:!1,close:function(){module_handler.removeModule("CANCEL_SESSION");module_handler.removeModule("EDIT_NOTE");module_handler.removeModule("EDIT_USER");$("#session_info").empty()}});$("#signup_dialog").dialog({autoOpen:!1,resizable:!1,width:640,modal:!0,show:{effect:"fade",duration:200},hide:{effect:"fade",duration:200},buttons:{Cancel:function(){$(this).dialog("close")},Register:function(){registerUser()}},
close:function(a,b){resetRegistrationFormErrors();$("#registration_form")[0].reset()}});$("#error_dialog").dialog({autoOpen:!1,resizable:!1,maxWidth:300,maxHeight:250,modal:!1,buttons:{Ok:function(){$(this).dialog("close")}}});$("#confirm_dialog").dialog({autoOpen:!1,resizable:!1,maxWidth:300,maxHeight:250,modal:!0,buttons:{Ok:function(){$(this).dialog("close")}}});showCalendarView();setUpLoginPannel();loadServiceSelector();showCalendar();$("#corecal_login").button().click(function(){processLogIn();
return!1});$("#register_btn").click(function(){$("#signup_dialog").dialog("open");return!1});$("#req_access_btn").button().click(function(){requestServiceAccess()});$(".login_txt_box").keypress(function(a){13==a.which&&(processLogIn(),a.preventDefault())});$("#login_form").submit(function(a){alert("Forum submitting")});$("#corecal_logout").button().click(function(){processLogOut()});$("#facility_select").change(function(){$("#equipment_select option").remove();$("#service_select option").remove();
$("#calendar").fullCalendar("removeEvents");resetRolePanel();getResourceList()});$("#equipment_select").change(function(){$("#service_select option").remove();getServiceList()});$("#service_select").change(function(){updateUserPermissions()});$("body").fadeIn("fast")});
function showCalendar(a){var b=!1,c=(new Date).getHours(),b=1==a?{month:!0,agendaWeek:!0,agendaDay:!0}:!1;a={theme:!0,firstDay:1,defaultView:"agendaWeek",header:{left:"prev,next today",center:"title",right:"month,agendaWeek,agendaDay"},slotMinutes:15,firstHour:c,allDaySlot:!1,selectable:b,selectHelper:!1,lazyFetching:!1,select:handleEventSelection,eventClick:handleEventClick,eventResize:handleEventResize,eventDrop:handleEventDrop,viewDisplay:handleViewDisplay,eventRender:renderEvent,events:getEvents};
$("#calendar").fullCalendar(a)}function refreshCalendar(){$("#calendar").fullCalendar("refetchEvents")}function deleteEvent(a){$("#calendar").fullCalendar("removeEvents",a)}function updateEvent(a){}
function getFacilityList(){$.ajax({url:"./php/getFacilities.php",type:"POST",dataType:"json",success:function(a){a.hasOwnProperty("error")?1==a.error?alert(a.message):($facilities=a.data,0<$facilities.length&&$("#facility_select").append($('<option value = ""></option>').html("Select one...")),$.each($facilities,function(a,c){$("#facility_select").append($("<option value ="+c.id+"></option>").html(c.label))})):alert("Error fetching data: Invalid reponse from the server.")}})}
function getFacilityStatistics(){var a=$("#facility_select option:selected").val();$.ajax({url:"./php/getFacilityStats.php",type:"POST",dataType:"json",data:{facility_id:a},success:function(a){a.hasOwnProperty("error")?1==a.error?alert(a.message):(a=a.data.usage,chart_options.series[0].data=a.values,chart_options.xAxis.categories=a.categories,null!=chart&&chart.destroy(),chart=new Highcharts.Chart(chart_options)):alert("Error fetching data: Invalid reponse from the server.")}})}
function getResourceList(){var a=$("#facility_select option:selected").val();$.ajax({url:"./php/getResources.php",type:"POST",dataType:"json",data:{facility_id:a},success:function(a){a.hasOwnProperty("error")?1==a.error?alert(a.message):($resources=a.data,0<$resources.length&&$("#equipment_select").append($('<option value = ""></option>').html("Select one...")),$.each($resources,function(a,b){$("#equipment_select").append($("<option value ="+b.id+"></option>").html(b.label))})):alert("Error fetching data: Invalid reponse from the server.")}})}
function getServiceList(){var a=$("#equipment_select option:selected").val();$.ajax({url:"./php/getServices.php",type:"POST",dataType:"json",data:{rid:a},success:function(a){a.hasOwnProperty("error")?1==a.error?alert(a.message):($services=a.data,$.each($services,function(a,b){$("#service_select").append($("<option value ="+b.id+"></option>").html(b.label))}),$("#service_select").trigger("change")):alert("Error fetching data: Invalid reponse from the server.")}})}
function renderEvent(a,b){b.attr("title",a.description)}function getEvents(a,b,c){var e=$("#equipment_select option:selected").val();$.ajax({url:"./php/getEvents.php",type:"POST",dataType:"json",data:{start:Math.round(a.getTime()/1E3),end:Math.round(b.getTime()/1E3),eq_id:e},success:function(a){a.hasOwnProperty("error")?1==a.error?alert(a.message):c(a.data):alert("Error fetching data: Invalid reponse from the server.")}})}
function handleEventSelection(a,b,c){$("#calendar").fullCalendar("unselect");createNewEvent(a,b,c)}function createNewEvent(a,b,c){var e=$("#service_select option:selected").val(),d={};d.s_time=Math.round(a.getTime()/1E3);d.e_time=Math.round(b.getTime()/1E3);d.serv_id=e;d.all_day=c?1:0;null==e?showErrorMsg("Service type not selected."):$.ajax({type:"POST",url:"./php/newEvent.php",data:d,dataType:"json",cache:!1,success:newEventCreatedHandler,error:newEventCreateErrorHandler})}
function newEventCreatedHandler(a){a.hasOwnProperty("error")?1==a.error?showErrorMsg(a.message):$("#calendar").fullCalendar("refetchEvents"):alert("Error: Invalid reponse from the server. Operation failed")}function newEventCreateErrorHandler(a,b,c){alert(c)}
function handleEventClick(a,b,c){resetDialogContent();$.ajax({type:"POST",url:"./php/getEventDetails.php",data:{id:a.id},dataType:"html",cache:!1,success:function(a){$("#session_info").append(a);showEventDetails(b)},error:function(){alert("Could not load info")}})}function showEventDetails(a){var b=$("#session_info_d").dialog("option","width");a=[a.clientX-b/2,a.clientY-20];$("#session_info_d").dialog("option","position",a);$("#session_info_d").dialog("open")}
function resetDialogContent(){$("#session_info").empty()}function handleEventResize(a,b,c,e){var d={};d.record_id=a.id;d.dayDelta=b;d.minuteDelta=c;$.ajax({type:"POST",url:"./php/resizeEvent.php",data:d,dataType:"json",cache:!1,success:function(a){a.hasOwnProperty("error")?1==a.error?(showErrorMsg(a.message),e()):$("#calendar").fullCalendar("refetchEvents"):(alert("Error: Invalid reponse from the server. Operation failed"),e())},error:function(){alert("Error updating event information");e()}})}
function handleEventDrop(a,b,c,e,d){var f={};f.record_id=a.id;f.dayDelta=b;f.minuteDelta=c;f.allDay=e;$.ajax({type:"POST",url:"./php/moveEvent.php",data:f,dataType:"json",cache:!1,success:function(a){a.hasOwnProperty("error")?1==a.error?(showErrorMsg(a.message),d()):$("#calendar").fullCalendar("refetchEvents"):(alert("Error: Invalid reponse from the server. Operation failed"),d())},error:function(){alert("Error updating event information");d()}})}function handleViewDisplay(a){clearUI()}
function clearUI(){$("#session_info_d").dialog("isOpen")&&$("#session_info_d").dialog("close");$("#user_options_window").dialog("close")}function showCalendarView(){clearUI();$("#calendar_view").show()}function setUpLoginPannel(){checkLogin()}
function processLogIn(){var a={};a.user=$("#username_txt").val();a.pass=$("#password_txt").val();$.ajax({type:"POST",url:"./php/loginProcessor.php",data:a,dataType:"json",cache:!1,success:loginHandler,error:function(){alert("Error logging in. Please try again later")}})}function checkLogin(){$.ajax({type:"POST",url:"./php/loginChecker.php",dataType:"json",cache:!1,success:checkLoginHandler,error:function(){alert("Error logging in. Please try again later")}})}
function checkLoginHandler(a,b,c){b=!1;a.hasOwnProperty("error")?1==a.error?alert(a.message):a.hasOwnProperty("data")?null!=a.data?(b=!0,$("#user_login").text(a.data.name),$("#user_last_log").text(a.data.last_active),$("#user_pi").text(a.data.pi),$("#user_type").text(a.data.type)):b=!1:b=!1:(alert("Error: Invalid reponse from the server. Operation failed"),b=!1);b?($("#log_in_panel").hide(),$("#logged_in_panel").fadeIn("fast"),$("#dashboard_role_panel").slideDown("fast")):($("#log_in_panel").fadeIn("fast"),
$("#logged_in_panel").hide(),$("#dashboard_role_panel").hide())}
function loginHandler(a,b,c){a.hasOwnProperty("error")?1==a.error?(showErrorMsg(a.message),resetPassword()):($("#log_in_panel").hide(),$("#logged_in_panel").fadeIn("fast"),$("#dashboard_role_panel").slideDown("fast"),$("#user_login").text(a.data.name),$("#user_last_log").text(a.data.last_active),$("#user_pi").text(a.data.pi),$("#user_type").text(a.data.type),updateUserPermissions(),resetLogInPanel()):alert("Error: Invalid reponse from the server. Operation failed")}
function processLogOut(){$.ajax({type:"POST",url:"./php/logoutProcessor.php",dataType:"json",cache:!1,success:function(a){a.hasOwnProperty("error")?1==a.error?alert(a.message):($("#log_in_panel").fadeIn("fast"),$("#logged_in_panel").hide(),$("#dashboard_role_panel").hide(),updateUserPermissions(),clearUI(),resetLogInPanel()):alert("Error: Invalid reponse from the server. Operation failed")},error:function(){alert("Error logging out. Please check your connection and try again")}})}
function resetLogInPanel(){$("#username_txt").val("");resetPassword()}function resetPassword(){$("#password_txt").val("")}
function processCancel(){var a={id:getRecordID()};$.ajax({type:"POST",url:"./php/eventCancel.php",dataType:"json",data:a,cache:!1,success:function(a){a.hasOwnProperty("error")?1==a.error?alert(a.message):(clearUI(),$("#calendar").fullCalendar("refetchEvents")):alert("Error: Invalid reponse from the server. Operation failed")},error:function(){alert("Cancel operation failed. Please check your connection and try again")}})}
function updateUserPermissions(){resetUI();var a=$("#service_select option:selected").val(),b={};b.serv_id=a;null!=a?$.ajax({type:"POST",url:"./php/getCalendarConfig.php",data:b,dataType:"json",cache:!1,success:function(a){if(a.hasOwnProperty("error"))if(1==a.error)setUserRole("N/A","black"),resetCalendar(0);else{var b=0,d=0,f=0,g="";a.data.hasOwnProperty("can_add")&&(b=a.data.can_add);a.data.hasOwnProperty("show_req_btn")&&(d=a.data.show_req_btn);a.data.hasOwnProperty("show_txt")&&(f=a.data.show_txt);
a.data.hasOwnProperty("txt")&&(g=a.data.txt);b?resetCalendar(1):resetCalendar(0);d&&showRequestAccessButton();f&&showPermission(g)}else setUserRole("N/A","black"),resetCalendar(0)},error:function(){setUserRole("N/A","black");resetCalendar(0)}}):(setUserRole("N/A","black"),resetCalendar(0))}function showRequestAccessButton(){$("#req_access_cont").show()}function resetUI(){resetRolePanel()}function resetRolePanel(){$("#user_role").text("");$("#role_txt_cont").hide();$("#req_access_cont").hide()}
function getRecordID(){return $("#e_record_id").attr("rec_id")}function showErrorMsg(a){$("#error_msg").text(a);$("#error_dialog").dialog("open")}function showConfirmMsg(a,b){$("#confirm_msg_head").text(a);$("#confirm_msg_body").text(b);$("#confirm_dialog").dialog("open")}function showPermission(a){$("#role_txt_cont").show();$("#user_role").fadeOut().text(a).fadeIn("slow")}function setUserRole(a,b){$("#user_role").fadeOut().text(a).fadeIn("slow");$("#user_role").css("color",b)}
function resetRegistrationFormErrors(){$([]).add($("#uname")).add($("#psw1")).add($("#psw2")).add($("#fname")).add($("#lname")).add($("#phone")).add($("#email1")).add($("#email2")).add($("#pi_name")).add($("#pi_email")).add($("#pi_phone")).add($("#pi_address_1")).add($("#pi_address_2")).add($("#pi_city")).add($("#pi_state")).add($("#pi_zip")).removeClass("ui-state-error");$("#reg_error_msg").text("")}
function registerUser(){var a={};a.uname=$("#uname").val();a.psw1=$("#psw1").val();a.psw2=$("#psw2").val();a.fname=$("#fname").val();a.lname=$("#lname").val();a.phone=$("#phone").val();a.email1=$("#email1").val();a.email2=$("#email2").val();a.pi_name=$("#pi_name").val();a.pi_email=$("#pi_email").val();a.pi_phone=$("#pi_phone").val();a.pi_address_1=$("#pi_address_1").val();a.pi_address_2=$("#pi_address_2").val();a.pi_city=$("#pi_city").val();a.pi_state=$("#pi_state").val();a.pi_zip=$("#pi_zip").val();
resetRegistrationFormErrors();$.ajax({type:"POST",url:"./php/userRegistration.php",dataType:"json",data:a,cache:!1,success:function(a){if(a.hasOwnProperty("error"))if(a.error)if(a.hasOwnProperty("data")){a=a.data;var c=a.field,e=a.msg;switch(a.type){case 1:$("#"+c).addClass("ui-state-error");$("#reg_error_msg").text(e);break;case 2:$("#reg_error_msg").text("Database error: "+e);break;default:$("#reg_error_msg").text("Unknown error")}}else alert("Invalid reponse from the servers. No error info sent.");
else $("#signup_dialog").dialog("close"),showConfirmMsg("Registration completed successfully.","You will be notified by e-mail when your account is approved by system administrator.");else alert("Error: Invalid reponse from the server. Operation failed")},error:function(){alert("Error creating an account. Please try again later")}})}
function requestServiceAccess(){var a=$("#service_select option:selected").val();$.ajax({type:"POST",url:"./php/requestAccess.php",dataType:"json",data:{id:a},cache:!1,success:function(a){a.hasOwnProperty("error")?a.error?showErrorMsg(a.message):(updateUserPermissions(),showConfirmMsg("Request submitted.","You will be notified by e-mail when your request is approved by facility administrator.")):alert("Error: Invalid reponse from the server. Operation failed")},error:function(){alert("Error requesting access. Please try again later")}})}
function resetCalendar(a){var b=$("#calendar").fullCalendar("getDate"),c=$("#calendar").fullCalendar("getView");$("#calendar").fullCalendar("destroy");showCalendar(a);$("#calendar").fullCalendar("changeView",c.name);$("#calendar").fullCalendar("gotoDate",b)}function getSelectedResource(){return $("#sel_res_id").attr("RID")}function loadServiceSelector(){var a=getSelectedResource();null!=a?preloadServiceSelector(a):getFacilityList()}
function preloadServiceSelector(a){$.ajax({url:"./php/getServiceSelectorContent.php",type:"POST",dataType:"json",data:{rid:a},success:function(a){if(a.hasOwnProperty("error"))if(1==a.error)alert(a.message);else{var c=null,e=null,d=null,f=null,g=null;if(a.hasOwnProperty("data")){a.data.hasOwnProperty("fac_array")&&(c=a.data.fac_array);a.data.hasOwnProperty("res_array")&&(e=a.data.res_array);a.data.hasOwnProperty("ser_array")&&(d=a.data.ser_array);a.data.hasOwnProperty("fac_id")&&(f=a.data.fac_id);
a.data.hasOwnProperty("res_id")&&(g=a.data.res_id);var h="";0<c.length&&$("#facility_select").append($('<option value = ""></option>').html("Select one..."));$.each(c,function(a,b){h="";null!=f&&b.id==f&&(h=" selected");$("#facility_select").append($("<option value ="+b.id+h+"></option>").html(b.label))});1<e.length&&$("#equipment_select").append($('<option value = ""></option>').html("Select one..."));$.each(e,function(a,b){h="";null!=g&&b.id==g&&(h=" selected");$("#equipment_select").append($("<option value ="+
b.id+h+"></option>").html(b.label))});$.each(d,function(a,b){$("#service_select").append($("<option value ="+b.id+"></option>").html(b.label))});$("#service_select").trigger("change")}else getFacilityList()}else alert("Error fetching data: Invalid reponse from the server.")},error:function(){alert("Error loadnig data. Please try again later.")}})};